server:
  port: 9095
spring:
  application:
    name: trello
  datasource:
    url: jdbc:postgresql://localhost:5432/trello
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 60
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  flyway:
    enabled: false